# Start with a base image containing Java runtime
FROM java:8

# Add Author info
LABEL maintainer="ssd018@gmail.com"

# Add a volume to /tmp
VOLUME /tmp

# The application's jar file
ARG JAR_FILE=target/webcuration-0.0.1-SNAPSHOT.jar
ARG KEY_FILE=./keystore.p12

# Add the application's jar to the container
ADD ${JAR_FILE} to-do-springboot.jar
ADD ${KEY_FILE} keystore.p12


# Run the jar file
ENTRYPOINT ["java","-jar","/to-do-springboot.jar"]